-- A SQL representation of a SeisBench `Pick` object (seisbench.util.annotations.Pick)


CREATE TABLE SBPICK 
 ( SBPID BIGSERIAL,
   NETWORK_CODE VARCHAR(2) NOT NULL,
   STATION_CODE VARCHAR(8) NOT NULL,
   LOCATION_CODE VARCHAR(2) NOT NULL,
   CHANNEL_CODE VARCHAR(5) NOT NULL,
   PHASE VARCHAR(4),
   MODEL_NAME VARCHAR(20) NOT NULL,
   WEIGHT_NAME VARCHAR(20) NOT NULL,
   WEIGHT_VERSION SMALLINT DEFAULT (1),
   PEAK_TIME DOUBLE PRECISION NOT NULL,
   PEAK_VALUE DOUBLE PRECISION,
   START_TIME DOUBLE PRECISION,
   END_TIME DOUBLE PRECISION,
   THRESHOLD DOUBLE PRECISION,
   LEAPCORR BOOLEAN DEFAULT ('TRUE'),
   RFLAG VARCHAR(2) DEFAULT ('A'),
   LDDATE TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
   
   CONSTRAINT SBPICK01 CHECK (sbpid > 0),
   CONSTRAINT SBPICK02 CHECK (rflag in ('a','h','f','A','H','F')),
   CONSTRAINT SBPICK03 CHECK (peak_value >= 0.0 and peak_value <= 1.0),
   CONSTRAINT SBPKEY01 PRIMARY KEY (SBPID)
 );